
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>ONEQCU - Reports</title>
  <link rel="stylesheet" href="../../styles/admin/style.css">
  <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet">
</head>
<body>

<?php $currentPage = 'reports'; ?>
<?php require __DIR__ . '/../../components/admin/sidebar.php'; ?>

  <div class="main">
    <div class="topbar">
      <div>
        <h1 class="page-title">REPORTS AND ANALYTICS</h1>
        <p class="page-sub">Generate comprehensive asset reports</p>
      </div>
      <div class="topbar-actions">
        <button class="outline-btn">SCHEDULE REPORT</button>
        <button class="add-btn">+ CUSTOM REPORT</button>
      </div>
    </div>

    <div class="stats-row">
      <div class="stat-card">
        <div class="stat-label">Reports Generated</div>
        <div class="stat-value">0</div>
        <div class="stat-sub">This month</div>
      </div>
      <div class="stat-card">
        <div class="stat-label">Scheduled Reports</div>
        <div class="stat-value">0</div>
        <div class="stat-sub">Automated reports</div>
      </div>
      <div class="stat-card">
        <div class="stat-label">Report Templates</div>
        <div class="stat-value">0</div>
        <div class="stat-sub green">Available templates</div>
      </div>
      <div class="stat-card">
        <div class="stat-label">Total Downloads</div>
        <div class="stat-value">0</div>
        <div class="stat-sub">All time</div>
      </div>
    </div>

    <div class="table-section">
      <h2 class="section-title">REPORT TEMPLATES</h2>
      <div class="report-grid">
        <div class="report-card">COMPLETE ASSET INVENTORY</div>
        <div class="report-card">ASSET BY DEPARTMENT</div>
        <div class="report-card">MAINTENANCE COST ANALYSIS</div>
        <div class="report-card">OVERDUE ITEMS REPORT</div>
        <div class="report-card">BORROWING ACTIVITY REPORT</div>
        <div class="report-card">ASSET UTILIZATION REPORT</div>
      </div>
    </div>

    <div class="table-section" style="margin-top: 20px;">
      <h2 style="font-size:15px; font-weight:600; margin-bottom:16px;">Recent Reports</h2>
      <table class="asset-table">
        <thead>
          <tr>
            <th>REPORT NAME</th>
            <th>TYPE</th>
            <th>GENERATED BY</th>
            <th>DATE GENERATED</th>
            <th>FORMAT</th>
            <th>ACTIONS</th>
          </tr>
        </thead>
        <tbody>
          <tr class="empty-row">
            <td colspan="6">No reports to display.</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <script src="../../scripts/admin/pages_script.js"></script>
</body>
</html>
