<?php
require_once __DIR__ . '/../../backend/middleware/requireAdmin.php';
?>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>ONEQCU | Admin Reports</title>
  <link rel="stylesheet" href="/1QCUPROJECT/styles/admin/admin-base.css">
  <link rel="stylesheet" href="/1QCUPROJECT/styles/admin/admin-sidebar.css">
  <link rel="stylesheet" href="/1QCUPROJECT/styles/admin/admin-layout.css">
  <link rel="stylesheet" href="/1QCUPROJECT/styles/admin/admin-toast.css">
  <link rel="stylesheet" href="/1QCUPROJECT/styles/admin/admin-table.css">
  <link rel="stylesheet" href="/1QCUPROJECT/styles/admin/admin-modal.css">
  <link rel="stylesheet" href="/1QCUPROJECT/styles/admin/admin-stats.css">
  <link rel="stylesheet" href="/1QCUPROJECT/styles/admin/admin-reports.css">
  <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&display=swap" rel="stylesheet">
</head>

<body>
  <?php $currentPage = 'reports'; ?>
  <?php require __DIR__ . '/../../components/admin/admin_sidebar.php'; ?>

  <div class="main">

    <div class="topbar">
      <div>
        <h1 class="page-title">REPORTS &amp; ANALYTICS</h1>
        <p class="page-sub">Generate comprehensive asset reports</p>
      </div>
      <div class="header">
        <div class="topbar-actions">
          <button class="add-btn" id="scheduleReportBtn">SCHEDULE REPORT</button>
        </div>
        <!-- Notification system will be inserted here by JavaScript -->
      </div>
    </div>

    <div class="stats-row">
      <div class="stat-card">
        <div class="stat-label">Reports Generated</div>
        <div class="stat-value" id="statReportsGenerated">0</div>
        <div class="stat-sub">This month</div>
      </div>
      <div class="stat-card">
        <div class="stat-label">Scheduled Reports</div>
        <div class="stat-value" id="statScheduled">0</div>
        <div class="stat-sub">Automated reports</div>
      </div>
      <div class="stat-card">
        <div class="stat-label">Report Templates</div>
        <div class="stat-value">9</div>
        <div class="stat-sub green">Available templates</div>
      </div>
      <div class="stat-card">
        <div class="stat-label">Total Reports Generated</div>
        <div class="stat-value" id="statTotalReports">0</div>
        <div class="stat-sub">All Time</div>
      </div>
    </div>

    <div class="table-section">
      <h2 class="section-title">REPORT TEMPLATES</h2>
      <div class="report-grid">

        <div class="report-card" onclick="generateReport('Complete Asset Inventory')">
          <div style="font-size:22px;margin-bottom:8px;">&#128230;</div>
          COMPLETE ASSET INVENTORY
        </div>

        <div class="report-card" onclick="generateReport('Asset Status Report')">
          <div style="font-size:22px;margin-bottom:8px;">&#128202;</div>
          ASSET STATUS REPORT
        </div>

        <div class="report-card" onclick="generateReport('Certified Assets Report')">
          <div style="font-size:22px;margin-bottom:8px;">&#9989;</div>
          CERTIFIED ASSETS REPORT
        </div>

        <div class="report-card" onclick="generateReport('Overdue Items Report')">
          <div style="font-size:22px;margin-bottom:8px;">&#9888;</div>
          OVERDUE ITEMS REPORT
        </div>

        <div class="report-card" onclick="generateReport('Maintenance Report')">
          <div style="font-size:22px;margin-bottom:8px;">&#128295;</div>
          MAINTENANCE REPORT
        </div>

        <div class="report-card" onclick="generateReport('Asset by Department')">
          <div style="font-size:22px;margin-bottom:8px;">&#127970;</div>
          ASSET BY DEPARTMENT
        </div>

        <div class="report-card" onclick="generateReport('Borrowing Activity Report')">
          <div style="font-size:22px;margin-bottom:8px;">&#8644;</div>
          BORROWING ACTIVITY REPORT
        </div>

        <div class="report-card" onclick="generateReport('Asset Utilization Report')">
          <div style="font-size:22px;margin-bottom:8px;">&#128200;</div>
          ASSET UTILIZATION REPORT
        </div>

        <div class="report-card" onclick="generateReport('Audit Logs Report')">
          <div style="font-size:22px;margin-bottom:8px;">&#128196;</div>
          AUDIT LOGS REPORT
        </div>

      </div>
    </div>

    <div class="table-section" style="margin-top:20px;">
      <h2 style="font-size:15px;font-weight:600;margin-bottom:16px;">Recent Reports</h2>
      <table class="asset-table">
        <thead>
          <tr>
            <th>REPORT NAME</th>
            <th>TYPE</th>
            <th>GENERATED BY</th>
            <th>DATE GENERATED</th>
            <th>FORMAT</th>
            <th>ACTIONS</th>
          </tr>
        </thead>
        <tbody id="reportsTableBody">
          <tr class="empty-row">
            <td colspan="6">No reports to display.</td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="table-section" style="margin-top:20px;">
      <h2 style="font-size:15px;font-weight:600;margin-bottom:16px;">Scheduled Reports</h2>
      <table class="asset-table">
        <thead>
          <tr>
            <th>SCHEDULE NAME</th>
            <th>REPORT TYPE</th>
            <th>FREQUENCY</th>
            <th>START DATE</th>
            <th>NEXT RUN</th>
            <th>RUN TIME</th>
            <th>STATUS</th>
            <th>ACTIONS</th>
          </tr>
        </thead>
        <tbody id="scheduledTableBody">
          <tr class="empty-row">
            <td colspan="8">No scheduled reports.</td>
          </tr>
        </tbody>
      </table>
    </div>

  </div>

  <!-- REPORT OPTIONS MODAL -->
  <div class="modal-overlay" id="reportOptionsModal">
    <div class="modal">
      <div class="modal-title" id="reportOptionsTitle">Generate Report</div>
      <div class="modal-divider"></div>
      <div class="modal-section-label">REPORT OPTIONS</div>

      <div class="form-full" id="optsDeptWrapper" style="display:none;">
        <label>Department</label>
        <select id="optsDept">
          <option value="">All Departments</option>
        </select>
      </div>

      <div class="form-full" id="optsScopeWrapper" style="display:none;">
        <label>Scope</label>
        <select id="optsScope">
          <option value="all">All (Borrows + Late Returns + Maintenance)</option>
          <option value="borrows">Overdue Borrows Only</option>
          <option value="late">Late Returns Only</option>
        </select>
      </div>

      <div class="modal-two-col">
        <div class="form-group">
          <label>Month <span style="color:#888;font-weight:400;font-size:11px;">(optional)</span></label>
          <select id="optsMonth">
            <option value="">All Months</option>
            <option value="01">January</option>
            <option value="02">February</option>
            <option value="03">March</option>
            <option value="04">April</option>
            <option value="05">May</option>
            <option value="06">June</option>
            <option value="07">July</option>
            <option value="08">August</option>
            <option value="09">September</option>
            <option value="10">October</option>
            <option value="11">November</option>
            <option value="12">December</option>
          </select>
        </div>
        <div class="form-group">
          <label>Year <span style="color:#888;font-weight:400;font-size:11px;">(optional)</span></label>
          <select id="optsYear">
            <option value="">All Years</option>
          </select>
        </div>
      </div>

      <div class="modal-buttons">
        <button class="modal-edit-btn" id="cancelReportOptionsBtn">CANCEL</button>
        <button class="modal-close-btn" id="confirmReportOptionsBtn">GENERATE PDF</button>
      </div>
    </div>
  </div>

  <!-- CUSTOM REPORT MODAL -->
  <div class="modal-overlay" id="customReportModal">
    <div class="modal">
      <div class="modal-title">Custom Report</div>
      <div class="modal-divider"></div>
      <div class="modal-section-label">REPORT DETAILS</div>

      <div class="form-full">
        <label>Report Name <span style="color:#dc2626;font-weight:700;">*</span></label>
        <input type="text" id="reportName" placeholder="e.g. Q1 Asset Summary">
      </div>

      <div class="modal-two-col">
        <div class="form-group">
          <label>Report Type <span style="color:#dc2626;font-weight:700;">*</span></label>
          <select id="reportType">
            <option value="">-- Select Type --</option>
            <option value="Complete Asset Inventory">Asset Inventory</option>
            <option value="Asset Status Report">Asset Status</option>
            <option value="Certified Assets Report">Certified Assets</option>
            <option value="Overdue Items Report">Overdue Items</option>
            <option value="Maintenance Report">Maintenance Report</option>
            <option value="Asset by Department">Asset by Department</option>
            <option value="Borrowing Activity Report">Borrowing Activity</option>
            <option value="Asset Utilization Report">Asset Utilization</option>
          </select>
          <select id="reportFormat">
            <option value="PDF">PDF</option>
          </select>
        </div>
      </div>

      <div class="form-full" id="customDeptWrapper" style="display:none;">
        <label>Department</label>
        <select id="customDept">
          <option value="">All Departments</option>
        </select>
      </div>

      <div class="form-full" id="customScopeWrapper" style="display:none;">
        <label>Scope</label>
        <select id="customScope">
          <option value="all">All (Borrows + Late Returns + Maintenance)</option>
          <option value="borrows">Overdue Borrows Only</option>
          <option value="late">Late Returns Only</option>
        </select>
      </div>

      <div class="modal-two-col">
        <div class="form-group">
          <label>Month <span style="color:#888;font-weight:400;font-size:11px;">(optional)</span></label>
          <select id="customMonth">
            <option value="">All Months</option>
            <option value="01">January</option>
            <option value="02">February</option>
            <option value="03">March</option>
            <option value="04">April</option>
            <option value="05">May</option>
            <option value="06">June</option>
            <option value="07">July</option>
            <option value="08">August</option>
            <option value="09">September</option>
            <option value="10">October</option>
            <option value="11">November</option>
            <option value="12">December</option>
          </select>
        </div>
        <div class="form-group">
          <label>Year <span style="color:#888;font-weight:400;font-size:11px;">(optional)</span></label>
          <select id="customYear">
            <option value="">All Years</option>
          </select>
        </div>
      </div>

      <div class="modal-buttons">
        <button class="modal-edit-btn" id="cancelCustomReportBtn">CANCEL</button>
        <button class="modal-close-btn" id="saveCustomReportBtn">GENERATE REPORT</button>
      </div>
    </div>
  </div>

  <!-- SCHEDULE REPORT MODAL -->
  <div class="modal-overlay" id="scheduleReportModal">
    <div class="modal">
      <div class="modal-title">Schedule Report</div>
      <div class="modal-divider"></div>
      <div class="modal-section-label">SCHEDULE DETAILS</div>

      <div class="form-full">
        <label>Report Name <span style="color:#dc2626;font-weight:700;">*</span></label>
        <input type="text" id="schedReportName" placeholder="e.g. Monthly Asset Summary">
      </div>

      <div class="modal-two-col">
        <div class="form-group">
          <label>Report Type <span style="color:#dc2626;font-weight:700;">*</span></label>
          <select id="schedReportType">
            <option value="">-- Select Type --</option>
            <option value="Complete Asset Inventory">Complete Asset Inventory</option>
            <option value="Asset Status Report">Asset Status</option>
            <option value="Certified Assets Report">Certified Assets</option>
            <option value="Overdue Items Report">Overdue Items</option>
            <option value="Maintenance Report">Maintenance Report</option>
            <option value="Asset by Department">Asset by Department</option>
            <option value="Borrowing Activity Report">Borrowing Activity</option>
            <option value="Asset Utilization Report">Asset Utilization</option>
            <option value="Audit Logs Report">Audit Logs</option>
          </select>
        </div>
        <div class="form-group">
          <label>Frequency <span style="color:#dc2626;font-weight:700;">*</span></label>
          <select id="schedFrequency">
            <option value="">-- Select Frequency --</option>
            <option>Daily</option>
            <option>Weekly</option>
            <option>Monthly</option>
            <option>Quarterly</option>
          </select>
        </div>
      </div>

      <div class="modal-two-col">
        <div class="form-group">
          <label>Start Date <span style="color:#dc2626;font-weight:700;">*</span></label>
          <input type="date" id="schedStartDate">
        </div>
        <div class="form-group">
          <label>Run Time <span style="color:#dc2626;font-weight:700;">*</span></label>
          <input type="time" id="schedRunTime" value="08:00">
        </div>
      </div>

      <div class="modal-buttons">
        <button class="modal-edit-btn" id="cancelScheduleBtn">CANCEL</button>
        <button class="modal-close-btn" id="saveScheduleBtn">SAVE SCHEDULE</button>
      </div>
    </div>
  </div>

  <!-- Toast -->
  <div class="toast" id="toast"></div>

  <script src="../../scripts/admin/reports/admin-reports.js"></script>
  <script src="../../scripts/admin/reports/admin-reports-scheduled.js"></script>
  <script src="../../scripts/admin/reports/admin-reports-modals.js"></script>
  <script src="../../scripts/admin/reports/admin-reports-scheduler.js"></script>
  <script src="../../scripts/admin/reports/admin-reports-init.js"></script>
</body>

</html>